# Generated by Django 3.0 on 2020-09-19 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comentario',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
