# Generated by Django 3.0 on 2020-09-25 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0003_post_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='comentario_aprobado',
        ),
    ]
