# Generated by Django 3.0 on 2020-09-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verdad',
            name='published_date',
        ),
        migrations.AddField(
            model_name='verdad',
            name='conclusion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='verdad',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='verdad',
            name='topic',
            field=models.CharField(choices=[('metodos_anticonceptivos', 'Metodos anticonceptivos'), ('masculinidades', 'Masculinidades'), ('relaciones_sexuales', 'Relaciones sexuales'), ('noviazgo', 'Noviazgo'), ('violencia', 'Violencia'), ('feminismo', 'Feminismo'), ('ETS', 'Enfermedades de transmisión sexual')], default='feminismo', max_length=30),
        ),
    ]
