# Generated by Django 3.0 on 2020-09-27 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myv', '0003_verdad_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verdad',
            name='published_date',
        ),
    ]
