# Generated by Django 3.0 on 2020-09-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myv', '0004_remove_verdad_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verdad',
            name='conclusion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='verdad',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='verdad',
            name='topic',
            field=models.CharField(choices=[('metodos_anticonceptivos', 'Metodos anticonceptivos'), ('masculinidades', 'Masculinidades'), ('relaciones_sexuales', 'Relaciones sexuales'), ('noviazgo', 'Noviazgo'), ('violencia', 'Violencia'), ('feminismo', 'Feminismo'), ('ETS', 'Enfermedades de transmisión sexual'), ('ESI', 'Educación Sexual')], default='feminismo', max_length=30),
        ),
    ]
