# Generated by Django 3.0 on 2020-09-28 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myv', '0005_auto_20200927_2048'),
        ('myv', '0005_auto_20200927_2043'),
    ]

    operations = [
    ]
