# Generated by Django 3.0 on 2020-09-27 23:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_auto_20200927_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(verbose_name='texo'),
        ),
        migrations.AlterField(
            model_name='new',
            name='imagen',
            field=models.URLField(verbose_name='imagen'),
        ),
    ]
