# Generated by Django 3.0 on 2020-09-28 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_auto_20200927_2051'),
        ('noticias', '0003_auto_20200927_2048'),
    ]

    operations = [
    ]
